# Generated by Django 5.0.6 on 2024-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_alter_loanrequest_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
