# Generated by Django 5.0.6 on 2024-07-09 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_alter_loanrequest_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
